/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package hospitalmanagement;

import java.awt.HeadlessException;
import java.awt.Image;
import java.io.File;
import java.io.FileInputStream;
import java.io.FileNotFoundException;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.PreparedStatement;
import java.sql.SQLException;
import javax.swing.Icon;
import javax.swing.ImageIcon;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.RowFilter;
import javax.swing.filechooser.FileNameExtensionFilter;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableRowSorter;
import net.proteanit.sql.DbUtils;



/**
 *
 * @author ajink
 */
public class LowerStaffDetail extends javax.swing.JFrame {

    /**
     * Creates new form LowerStaffDetail
     */
    public LowerStaffDetail() {
        initComponents();
        showTableData();
    }
String s;
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jButton5 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        eid = new javax.swing.JTextField();
        city = new javax.swing.JTextField();
        firstname = new javax.swing.JTextField();
        age = new javax.swing.JTextField();
        lastname = new javax.swing.JTextField();
        aadhar_no = new javax.swing.JTextField();
        address = new javax.swing.JTextField();
        search = new javax.swing.JTextField();
        phonenum = new javax.swing.JTextField();
        etype = new javax.swing.JComboBox<>();
        gender = new javax.swing.JComboBox<>();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        adddoctor = new javax.swing.JButton();
        removedoctor = new javax.swing.JButton();
        update = new javax.swing.JButton();
        employeephoto = new javax.swing.JLabel();
        jButton4 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        jPanel1.setBackground(new java.awt.Color(0, 0, 153));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Lower Staff Detail");

        jButton5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/home.png"))); // NOI18N
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 328, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 512, Short.MAX_VALUE)
                .addComponent(jButton5, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(57, 57, 57))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addComponent(jButton5, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(21, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel1);
        jPanel1.setBounds(237, 6, 965, 100);

        jLabel2.setBackground(new java.awt.Color(0, 153, 204));
        jLabel2.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 153, 204));
        jLabel2.setText("First Name");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(20, 190, 100, 24);

        jLabel3.setBackground(new java.awt.Color(0, 153, 204));
        jLabel3.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(0, 153, 204));
        jLabel3.setText("Last Name");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(20, 230, 110, 24);

        jLabel4.setBackground(new java.awt.Color(0, 153, 204));
        jLabel4.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(0, 153, 204));
        jLabel4.setText("Aadhar no.");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(19, 281, 90, 24);

        jLabel5.setBackground(new java.awt.Color(0, 153, 204));
        jLabel5.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(0, 153, 204));
        jLabel5.setText("Address");
        getContentPane().add(jLabel5);
        jLabel5.setBounds(19, 329, 80, 24);

        jLabel6.setBackground(new java.awt.Color(0, 153, 204));
        jLabel6.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(0, 153, 204));
        jLabel6.setText("Search");
        getContentPane().add(jLabel6);
        jLabel6.setBounds(20, 370, 57, 24);

        jLabel7.setBackground(new java.awt.Color(0, 153, 204));
        jLabel7.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(0, 153, 204));
        jLabel7.setText("Age");
        getContentPane().add(jLabel7);
        jLabel7.setBounds(380, 180, 50, 24);

        jLabel8.setBackground(new java.awt.Color(0, 153, 204));
        jLabel8.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(0, 153, 204));
        jLabel8.setText("Phone no.");
        getContentPane().add(jLabel8);
        jLabel8.setBounds(370, 280, 82, 24);

        jLabel9.setBackground(new java.awt.Color(0, 153, 204));
        jLabel9.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(0, 153, 204));
        jLabel9.setText("City");
        getContentPane().add(jLabel9);
        jLabel9.setBounds(370, 330, 50, 24);

        jLabel10.setBackground(new java.awt.Color(0, 153, 204));
        jLabel10.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(0, 153, 204));
        jLabel10.setText("Gender");
        getContentPane().add(jLabel10);
        jLabel10.setBounds(380, 230, 60, 24);

        jLabel11.setBackground(new java.awt.Color(0, 153, 204));
        jLabel11.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(0, 153, 204));
        jLabel11.setText("Staff Type");
        getContentPane().add(jLabel11);
        jLabel11.setBounds(370, 370, 83, 24);

        jLabel12.setBackground(new java.awt.Color(0, 153, 204));
        jLabel12.setFont(new java.awt.Font("Dialog", 1, 48)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(0, 102, 204));
        jLabel12.setText("STAFF ID");
        getContentPane().add(jLabel12);
        jLabel12.setBounds(237, 124, 214, 44);

        jLabel13.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/EMPLOYEESDETAILS.png"))); // NOI18N
        getContentPane().add(jLabel13);
        jLabel13.setBounds(30, 0, 170, 140);
        getContentPane().add(eid);
        eid.setBounds(460, 130, 260, 40);
        getContentPane().add(city);
        city.setBounds(460, 320, 270, 30);
        getContentPane().add(firstname);
        firstname.setBounds(120, 190, 240, 30);
        getContentPane().add(age);
        age.setBounds(460, 180, 260, 30);
        getContentPane().add(lastname);
        lastname.setBounds(120, 230, 240, 30);

        aadhar_no.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                aadhar_noActionPerformed(evt);
            }
        });
        getContentPane().add(aadhar_no);
        aadhar_no.setBounds(120, 270, 240, 30);
        getContentPane().add(address);
        address.setBounds(120, 320, 240, 30);

        search.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                searchKeyReleased(evt);
            }
        });
        getContentPane().add(search);
        search.setBounds(120, 370, 240, 30);
        getContentPane().add(phonenum);
        phonenum.setBounds(460, 270, 260, 30);

        etype.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Select Staff Type", "Nurse", "Therapist ", "Medical Assistants", "Pharmacists", "Accountant", "Food Service", "volunteers ", "ward clerks " }));
        getContentPane().add(etype);
        etype.setBounds(460, 360, 170, 30);

        gender.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Select Gender", "Male", "Female", "Other" }));
        getContentPane().add(gender);
        gender.setBounds(460, 230, 150, 30);

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4", "Title 5", "Title 6", "Title 7", "Title 8"
            }
        ));
        jTable1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable1MouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTable1);

        getContentPane().add(jScrollPane1);
        jScrollPane1.setBounds(372, 400, 820, 230);

        adddoctor.setFont(new java.awt.Font("Dialog", 0, 24)); // NOI18N
        adddoctor.setForeground(new java.awt.Color(0, 153, 204));
        adddoctor.setText("ADD EMPLOYEE");
        adddoctor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                adddoctorActionPerformed(evt);
            }
        });
        getContentPane().add(adddoctor);
        adddoctor.setBounds(30, 440, 330, 50);

        removedoctor.setFont(new java.awt.Font("Dialog", 0, 24)); // NOI18N
        removedoctor.setForeground(new java.awt.Color(0, 153, 204));
        removedoctor.setText("REMOVE EMPLOYEE");
        removedoctor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                removedoctorActionPerformed(evt);
            }
        });
        getContentPane().add(removedoctor);
        removedoctor.setBounds(30, 500, 330, 50);

        update.setFont(new java.awt.Font("Dialog", 0, 24)); // NOI18N
        update.setForeground(new java.awt.Color(0, 153, 204));
        update.setText("UPDATE EMPLOYEE");
        update.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                updateActionPerformed(evt);
            }
        });
        getContentPane().add(update);
        update.setBounds(30, 560, 330, 50);

        employeephoto.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        getContentPane().add(employeephoto);
        employeephoto.setBounds(880, 120, 230, 210);

        jButton4.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jButton4.setForeground(new java.awt.Color(0, 153, 204));
        jButton4.setText("Browse");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton4);
        jButton4.setBounds(925, 340, 150, 40);

        setSize(new java.awt.Dimension(1216, 648));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
         adminPanel ap=new adminPanel();
        ap.setVisible(true);
        this.dispose(); 
    }//GEN-LAST:event_jButton5ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        JFileChooser fileChooser = new JFileChooser();
        fileChooser.setCurrentDirectory(new File(System.getProperty("user.home")));
        FileNameExtensionFilter filter = new FileNameExtensionFilter("*.IMAGE", "jpg","gif","png");
        fileChooser.addChoosableFileFilter(filter);
        int result = fileChooser.showSaveDialog(null);
        if(result == JFileChooser.APPROVE_OPTION){
            File selectedFile = fileChooser.getSelectedFile();
            String path = selectedFile.getAbsolutePath();
            employeephoto.setIcon(ResizeImage(path));
            s = path;
        }
        else if(result == JFileChooser.CANCEL_OPTION){
            System.out.println("No Data");
        }
    }//GEN-LAST:event_jButton4ActionPerformed
public void showTableData(){
    try{
            Class.forName("com.mysql.cj.jdbc.Driver");
            Connection conn=DriverManager.getConnection("jdbc:mysql://localhost:3308/hospitalmanagementsystem?useSSL=false","root","ROOT");
            PreparedStatement pst = conn.prepareStatement("SELECT * FROM hospitalmanagementsystem.employees");
 ResultSet rs=pst.executeQuery();         
jTable1.setModel(DbUtils.resultSetToTableModel(rs));
    }
    catch(ClassNotFoundException | SQLException e){
            JOptionPane.showMessageDialog(this, e.getMessage());
        }
}
    private void adddoctorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_adddoctorActionPerformed
          try{
            Class.forName("com.mysql.cj.jdbc.Driver");
            Connection conn=DriverManager.getConnection("jdbc:mysql://localhost:3308/hospitalmanagementsystem?useSSL=false","root","ROOT");
            PreparedStatement pst = conn.prepareStatement( "insert into employees"+"(E_id,firstname,lastname,address,aadhar_no,agee,gender,city,phoneno,emptype,employeephoto)"+" values(?,?,?,?,?,?,?,?,?,?,?)");
          FileInputStream is = new FileInputStream(new File(s));
            pst.setString(1,eid.getText());
            pst.setString(2,firstname.getText());
            pst.setString(3,lastname.getText());
            pst.setString(4,address.getText());
            pst.setString(5,aadhar_no.getText());
            pst.setString(6,age.getText());
            pst.setString(7, (String) gender.getSelectedItem());
            pst.setString(8,city.getText());
             pst.setString(9,phonenum.getText());
             pst.setString(10, (String) etype.getSelectedItem());
              pst.setBinaryStream(11,is,(int)s.length());
              
            pst.executeUpdate();
            JOptionPane.showMessageDialog(this,"Record Inserted Sucessfully");
            showTableData();
           eid.setText(null);
           firstname.setText(null);
           lastname.setText(null);
            address.setText(null);
           aadhar_no.setText(null);
           age.setText(null);
           gender.setSelectedIndex(0);
          city.setText(null);
           phonenum.setText(null);
           employeephoto.setText(null);
            }
        catch(HeadlessException | FileNotFoundException | ClassNotFoundException | SQLException e){
            JOptionPane.showMessageDialog(this, e.getMessage());
        }
    }//GEN-LAST:event_adddoctorActionPerformed

    private void aadhar_noActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_aadhar_noActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_aadhar_noActionPerformed

    private void updateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_updateActionPerformed
       try{
          Class.forName("com.mysql.cj.jdbc.Driver");
     
            Connection conn=DriverManager.getConnection("jdbc:mysql://localhost:3308/hospitalmanagementsystem?useSSL=false","root","ROOT");
            PreparedStatement pst = conn.prepareStatement("UPDATE employees SET firstname=?,lastname=?,address=?,aadhar_no=?,agee=?,gender=?,city=?,phoneno=?,emptype=? WHERE E_id=?");
           
            pst.setString(1,firstname.getText());
            pst.setString(2,lastname.getText());
            pst.setString(3,address.getText());
            pst.setString(4,aadhar_no.getText());
            pst.setString(5,age.getText());
            pst.setString(6, (String) gender.getSelectedItem());
           pst.setString(7,city.getText());
            pst.setString(8,phonenum.getText());
            pst.setString(9, (String) etype.getSelectedItem());
            pst.setString(10,eid.getText());
          
            pst.executeUpdate();
            JOptionPane.showMessageDialog(this,"Record Updated Sucessfully");
             showTableData();
  eid.setText(null);
           firstname.setText(null);
           lastname.setText(null);
            address.setText(null);
           aadhar_no.setText(null);
           age.setText(null);
           gender.setSelectedIndex(0);
          city.setText(null);
           phonenum.setText(null);
           etype.setSelectedIndex(0);
           
       }

        catch (HeadlessException | ClassNotFoundException | SQLException e)
        {
            JOptionPane.showMessageDialog(null, e);
        }
    }//GEN-LAST:event_updateActionPerformed

    private void removedoctorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_removedoctorActionPerformed
          try{
            Class.forName("com.mysql.cj.jdbc.Driver");
            Connection conn=DriverManager.getConnection("jdbc:mysql://localhost:3308/hospitalmanagementsystem?useSSL=false","root","ROOT");
            PreparedStatement pst = conn.prepareStatement("delete from employees where E_id =?");
            pst.setString(1,eid.getText());
            pst.executeUpdate();
            JOptionPane.showMessageDialog(this,"Record Deleted Sucessfully");
            showTableData();
            eid.setText(null);
           firstname.setText(null);
           lastname.setText(null);
            address.setText(null);
           aadhar_no.setText(null);
           age.setText(null);
           gender.setSelectedIndex(0);
          city.setText(null);
           phonenum.setText(null);
           etype.setSelectedIndex(0);
           
        }
        catch(HeadlessException | ClassNotFoundException | SQLException e){
            JOptionPane.showMessageDialog(this, e.getMessage());
        }
    }//GEN-LAST:event_removedoctorActionPerformed

    private void jTable1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable1MouseClicked
        int SelectedRow =jTable1.getSelectedRow();
           DefaultTableModel table=(DefaultTableModel)jTable1.getModel();
           eid.setText(table.getValueAt(SelectedRow, 0).toString());
            firstname.setText(table.getValueAt(SelectedRow, 1).toString());
             lastname.setText(table.getValueAt(SelectedRow, 2).toString()); 
             
address.setText(table.getValueAt(SelectedRow, 3).toString());
aadhar_no.setText(table.getValueAt(SelectedRow, 4).toString());
age.setText(table.getValueAt(SelectedRow, 5).toString());
gender.setSelectedItem(table.getValueAt(SelectedRow, 6).toString());
city.setText(table.getValueAt(SelectedRow, 7).toString());
phonenum.setText(table.getValueAt(SelectedRow, 8).toString());
etype.setSelectedItem(table.getValueAt(SelectedRow, 9).toString());
employeephoto.setIcon((Icon) table.getValueAt(SelectedRow, 10));
    }//GEN-LAST:event_jTable1MouseClicked

    private void searchKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_searchKeyReleased
        DefaultTableModel table=(DefaultTableModel)jTable1.getModel();
        String search1=search.getText().toLowerCase();
        TableRowSorter<DefaultTableModel> tr=new TableRowSorter<>(table);
        jTable1.setRowSorter(tr);
        tr.setRowFilter(RowFilter.regexFilter(search1));   // TODO 
    }//GEN-LAST:event_searchKeyReleased

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(LowerStaffDetail.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(LowerStaffDetail.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(LowerStaffDetail.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(LowerStaffDetail.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            @Override
            public void run() {
                new LowerStaffDetail().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField aadhar_no;
    private javax.swing.JButton adddoctor;
    private javax.swing.JTextField address;
    private javax.swing.JTextField age;
    private javax.swing.JTextField city;
    private javax.swing.JTextField eid;
    private javax.swing.JLabel employeephoto;
    private javax.swing.JComboBox<String> etype;
    private javax.swing.JTextField firstname;
    private javax.swing.JComboBox<String> gender;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField lastname;
    private javax.swing.JTextField phonenum;
    private javax.swing.JButton removedoctor;
    private javax.swing.JTextField search;
    private javax.swing.JButton update;
    // End of variables declaration//GEN-END:variables

public ImageIcon ResizeImage(String imgPath){
        ImageIcon MyImage = new ImageIcon(imgPath);
        Image img = MyImage.getImage();
        Image newImage = img.getScaledInstance(employeephoto.getWidth(), employeephoto.getHeight(),Image.SCALE_SMOOTH);
        ImageIcon image = new ImageIcon(newImage);
        return image;
}
}